app/catalog/models.py
from app import db
from datetime import datetime

class Publication(db.Model):
    __tablename__ = 'publication'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return f'The ID is {self.id} and name is {self.name}'


class Book(db.Model):
    __tablename__ = 'book'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False, index=True)
    author = db.Column(db.String(350))
    avg_rating = db.Column(db.Float)
    format = db.Column(db.String(80))
    image = db.Column(db.String(100), unique=True)
    num_pages = db.Column(db.Integer)
    pub_date = db.Column(db.DateTime, default=datetime.utcnow())

    # Foreign key with id in publication table as primary
    pub_id = db.Column(db.Integer, db.ForeignKey("publication.id"))

    def __init__(self, title, author, avg_rating, format, image, num_pages, pub_id):
        self.title = title
        self.author = author
        self.avg_rating = avg_rating
        self.format = format
        self.image = image
        self.num_pages = num_pages
        self.pub_id = pub_id

    def __repr__(self):
        return f'Title: {self.title} | ' \
               f'Author: {self.author} | ' \
               f'Rating: {self.avg_rating} | ' \
               f'Format: {self.format} | ' \
               f'Image: {self.image} | ' \
               f'num_pages: {self.num_pages} | ' \
               f'pub_id: {self.pub_id}'

app/catalog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, FloatField
from wtforms.validators import DataRequired


class EditBookForm(FlaskForm):
    title = StringField("Enter new title: ", validators=[DataRequired()])
    format = StringField("Enter new format: ", validators=[DataRequired()])
    num_pages = StringField("Enter num_pages: ", validators=[DataRequired()])
    update = SubmitField("Update")


class CreateBookForm(FlaskForm):
    title = StringField('Title: ', validators=[DataRequired()])
    author = StringField("Author: ", validators=[DataRequired()])
    avg_rating = FloatField("Avg Rating: ", validators=[DataRequired()])
    format = StringField("Format: ", validators=[DataRequired()])
    image = StringField("Image: ", validators=[DataRequired()])
    num_page = IntegerField("Num of pages: ", validators=[DataRequired()])
    pub_id = IntegerField("Publisher ID: ", validators=[DataRequired()])
    create = SubmitField("Create book")

app/catalog/__init__.py
# app/catalog/__init__

from flask import Blueprint
main = Blueprint('main', __name__, template_folder='templates')


from app.catalog import routes

app/catalog/routes.py
from app.catalog import main
from app.catalog.models import Book, Publication
from flask import render_template, url_for, flash, request, redirect
from flask_login import login_required
from app import db
from app.catalog.forms import EditBookForm, CreateBookForm

@main.route('/')
def display_books():
    books = Book.query.all()
    return render_template('home.html', books=books)


@main.route('/display/publisher/<publisher_id>')
def display_publisher(publisher_id):
    publisher = Publication.query.filter_by(id=publisher_id).first()
    publishers_books = Book.query.filter_by(pub_id=publisher_id).all()
    return render_template('publisher.html', publisher=publisher, publishers_books=publishers_books)


@main.route('/delete/book/<book_id>', methods=['GET', 'POST'])
@login_required
def delete_book(book_id):
    book = Book.query.get(book_id)

    if request.method == 'POST':
        db.session.delete(book)
        db.session.commit()
        flash('Book successfully deleted.')
        return redirect(url_for('main.display_books'))

    return render_template('delete_book.html', book=book, book_id=book_id)

@main.route('/edit/book/<book_id>', methods=['GET', 'POST'])
@login_required
def edit_book(book_id):
    book = Book.query.get(book_id)
    editBookForm = EditBookForm(obj=book)

    if editBookForm.validate_on_submit():
        book.title = editBookForm.title.data
        book.format = editBookForm.format.data
        book.num_pages = editBookForm.num_pages.data
        db.session.add(book)
        db.session.commit()
        flash("Book details updated successfully!")
        return redirect(url_for('main.display_books'))

    return render_template("edit_book.html", editBookForm=editBookForm, book_id=book_id)

@main.route("/create/book/<pub_id>", methods=['GET', 'POST'])
@login_required
def create_book(pub_id):
    createBookForm = CreateBookForm()
    createBookForm.pub_id.data = pub_id  # To populate the pub_id textbox in the Form

    if createBookForm.validate_on_submit():
        book = Book(createBookForm.title.data,
                    createBookForm.author.data,
                    createBookForm.avg_rating.data,
                    createBookForm.format.data,
                    createBookForm.image.data,
                    createBookForm.num_page.data,
                    createBookForm.pub_id.data)
        db.session.add(book)
        db.session.commit()
        flash("Book added successfully..!")
        return redirect(url_for('main.display_publisher', publisher_id=pub_id))

    return render_template('create_book.html', createBookForm=createBookForm, pub_id=pub_id)

app/catalog/templates/create_book.html
{% extends "layout.html" %}
{% block content %}
    <h3>Create new book</h3>
    <hr>
    {{ createBookForm.hidden_tag() }}
    {{ wtf.quick_form(createBookForm) }}
{% endblock %}

app/catalog/templates/delete_book.html
{% extends "layout.html" %}

{% block content %}

    <h3>Delete this book?</h3>
    <hr>
    <h4>{{ book.title }}</h4>
    <p>{{ book.author }}</p>
    <p>{{ book.format }}</p>
    <form action="{{ url_for('main.delete_book', book_id=book_id) }}" method="post">
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>

{% endblock %}

app/catalog/templates/edit_book.html
{% extends "layout.html" %}

{% block content %}
    <h3>Edit book {{ book_id }}</h3>
    <hr>
    {{ editBookForm.hidden_tag() }}
    {{ wtf.quick_form(editBookForm) }}
{% endblock %}

app/catalog/templates/home.html
{% extends "layout.html" %}

{% block content %}
    <div class="row pt-5">
        {% for book in books %}
                <div class="col-md-4">
                    <div class="ml-5 p-3">
                        <img src="static/img/{{ book.image }}" alt="{{ book.image }}" width="200" height="190">
                        <h4>{{ book.title }}</h4>
                        <p>{{ book.author }}</p>
                        <p>{{ book.format }}</p>
                        <p>{{ book.avg_rating }}</p>
                        <p>{{ book.num_pages }}</p>
                        <a href="{{ url_for('main.display_publisher', publisher_id=book.pub_id) }}">Publisher ID: {{ book.pub_id }}</a>
                        <br>
                        <span class="badge badge-success">
                            <a href="{{ url_for('main.create_book', pub_id=book.pub_id) }}" class="text-white"  >Create</a>
                        </span>
                        <span class="badge badge-primary">
                            <a href="{{ url_for('main.edit_book', book_id=book.id) }}" class="text-white"  >Edit</a>
                        </span>
                        <span class="badge badge-danger">
                            <a href="{{ url_for('main.delete_book', book_id=book.id) }}" class="text-white"  >Delete</a>
                        </span>

                    </div>
                </div>
        {% endfor %}
    </div>
{% endblock %}

app/catalog/templates/layout.html
{% import "bootstrap/wtf.html" as wtf %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <title>Books Inc</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/myStyles.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300&display=swap" rel="stylesheet">
    {% endblock head %}
</head>
<body>
{% block body %}
    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a style="text-decoration: none" class="navbar-brand" href="{{ url_for('main.display_books') }}">
                    <h3>Books around the corner</h3>
                </a>
                <ul class="navbar-nav">
                    <li><a class="nav-item nav-link" href="{{ url_for('main.display_books') }}">Home</a></li>
                    <li><a class="nav-item nav-link" href="{{ url_for('authentication.register_user') }}">Register</a></li>

                    {% if current_user.is_authenticated %}
                    <li><a class="nav-item nav-link" href="{{ url_for('authentication.logout_the_user') }}">Log out</a></li>
                    {% else %}
                    <li><a class="nav-item nav-link" href="{{ url_for('authentication.login_the_user') }}">Sign In</a></li>
                    {% endif %}

                    <li>
                        <a class="nav-item nav-link" href="">
                        <!-- IMP: current_user is a variable given by Flask which represent Current user  -->
                        {% if current_user.is_authenticated %}
                            LoggedIn as: <b style="color: deeppink">{{ current_user.user_name.title() }}</b>
                        {% else %}
                            Not LoggedIn
                        {% endif %}
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    {% endblock navbar %}

    <div class="pt-3">
    {% for message in get_flashed_messages() %}
        <div class="container alert alert-info alert-dismissible" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">Close</button>
        </div>
    {% endfor %}
    </div>


    <div class="container">
        {% block content %} {% endblock content %}
    </div>

    {% block footer %}
        <footer>
            <div class="container">
                <br>
                <p class="text-center small text-white">Books around the corner | sanketsy | 2021</p>
            </div>
        </footer>
    {% endblock footer %}
{% endblock body %}
</body>
</html>

app/catalog/templates/publisher.html
{% extends "layout.html" %}

{% block content %}
    <div class="pt-5">
        <h3>Books by {{ publisher.name }}</h3>
        <ul>
            {% for book in publishers_books %}
                <li type="1">
                    {{ book.title }} by {{ book.author }}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}